# =========================================================================== 
# =========================================================================== 

# ==============================
# COMMON
# ==============================
INIT_XYZ = [0.1, 0.0, 0.0]
DT = 0.01
T_SKIP = 500
T_END = 1000
CUTOFF = 1e50
BATCH_SIZE = 6000
TOLERANCE = 0.05

# ==============================
# GRAPH
# ==============================
SIZE = 1


# ==============================
# SPACE
# ==============================
SIM_NUM = 4000000
PRINT_EVERY = 10000
RANDOM_STATE = 1
FILENAME = "sim_results_space.txt"


# ==============================
# UMAP PARAMETERS:
# ==============================
N_NEIGHBORS = 15 # n_neighbors controls how UMAP balances local vs global structure.
MIN_DIST = 0.1 # min_dist controls how tightly points are packed together.


# ==============================
# RANDOM FOREST PARAMETERS:
# ==============================
TEST_SIZE = 0.2
N_ESTIMATORS = 100 



# ==============================
# FITTER
# ==============================
SPREAD = 0.25
POPSIZE = 100
MAXITER = 300
# =========================================================================== 
# =========================================================================== 
